# Generated by Django 5.2.1 on 2025-05-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='NO', upload_to='images'),
            preserve_default=False,
        ),
    ]
